import './Button/Button.stories';
import './Welcome/Welcome.stories';
import './Accordion/Accordion.stories';
import './LoadingSpinner/Spinner.stories';
import './Radio/Radio.stories';
import './Grid/Grid.stories';
import './AvatarCollection/AvatarCollection.stories';
import './TextInput/TextInput.stories';
// import './Modal/CenteredModal.stories';
import './Progress/Progress.stories';